### ISSUE TITLE
Decrypt content with fixed salt

### ISSUE THREAD

**Issue by cll0ud** [LucasSloan/passwordbasedencryption#1]
Hi there! I've got some content encrypted with Jasypt that needs to be used in a Go application. Your code works pretty good for me (thanks!) but I've got some data that was encrypted with fixed salt as well.

I tried replacing the random salt with my fixed string but I can't get it to work:

```go
func Decrypt(password string, obtenationIterations int, cipherText string, salt string) (string, error) {
	msgBytes, err := base64.StdEncoding.DecodeString(cipherText)
	if err != nil {
		return "", err
	}

	//salt := msgBytes[:8]
	encText := msgBytes[8:]

	dk, iv := getDerivedKey(password, salt, obtenationIterations)
	block,err := des.NewCipher(dk)

	if err != nil {
		return "", err
	}

	//decrypt
	decrypter := cipher.NewCBCDecrypter(block, iv)
	decrypted := make([]byte, len(encText))
	decrypter.CryptBlocks(decrypted, encText)

	decryptedString := strings.TrimRight(string(decrypted), "\x01\x02\x03\x04\x05\x06\x07\x08")

	return decryptedString, nil
}
```

I encrypted the following (in Jasypt) for tests:

- Content: `encryption test`
- Password: `password`
- Salt: `fixed_salt`
- The encryption result is: `IcszAY8NRJf6ANt152Fifg==`

When decrypting on Go with the above code I get: `�p�=��`

Any tips?

**Comment by LucasSloan** [comment]
My best guess is that if you're using a fixed salt jasypt is silently trimming it down to 8 bytes.  I'd suggest you go check out https://github.com/jasypt/jasypt to see how it is that they handle it.  If you figure it out, I'd be happy to accept a pull request!

**Comment by cll0ud** [comment]
Hey, you were right! I got it working after some small changes. I'll send a pull request after cleaning up my code. Thank you so much! :)
